### ISSUE TITLE
QPlaceholder CSS conflcts with Quasar CSS

### ISSUE THREAD

**Issue by onurkose** [hawkeye64/app-extension-qplaceholder#2] opened 2019-08-09 07:52 UTC
Hi, there was strange things happening with my forms after I installed the extension.
I've tested it with and without installing it and it seems the extension creating some trouble for q-input.

Here is the [screenshot](https://recordit.co/HAz0T2Sfm9).
http://g.recordit.co/HAz0T2Sfm9.gif

**Comment by hawkeye64** [comment] 2019-08-09 13:16
I can't really tell what the issue is. Is it slow to draw out q-input? If so, consider removing the `animated` property from q-placeholder.

**Comment by onurkose** [comment] 2019-08-09 14:13
These are the things I noted;

- Standard input type doesn't renders with the line under
- Filled input has only sides as filled, center part has a big white area and there's no line under
- Outlined input also has issues in the center part

Extension is only installed when these are happening and it's fresh/blank quasar app.
There's no q-placeholder component in the document.
I've tried removing the extension from quasar app on fresh installation and everything went back normal.

**Comment by hawkeye64** [comment] 2019-08-16 12:39
Can you give me a screen shot or something so I can visualize it better?

**Comment by onurkose** [comment] 2019-08-18 16:41
Normal behaviour:
![`Normal behaviour`](https://i.imgur.com/kdNLLPN.png)
When installed the extension:
![`When installed the extension`](https://i.imgur.com/HNByfK4.png)

**Comment by hawkeye64** [comment] 2019-08-24 13:19
Putting a fix together for this right now. Release will be available soon.

**Comment by hawkeye64** [comment] 2019-08-24 13:38
Fixed in 1.0.0-alpha.4
@onurkose Thanks for finding this :heart:

**Closed as completed by hawkeye64** 2019-08-24 13:38 UTC

**Comment by hawkeye64** [comment] 2019-08-24 14:37
![image](https://user-images.githubusercontent.com/10262924/63638847-72f43f80-c64a-11e9-8474-d449df1acd1c.png)
